@startuml
!include styles.puml
"Node.js StateStore" -> "Node.js StateStore": init => sequencer.transport.beat = 0
"SuperCollider TempoClock" -> "SuperCollider StateStore": dispatch(SEQUENCER_TRANSPORT_UPDATED)
"SuperCollider StateStore" -> "Node.js StateStore" : dispatch(SEQUENCER_TRANSPORT_UPDATED)
"Node.js StateStore" -> "Node.js StateStore": reduce_action => sequencer.transport.beat = 1
"Node.js StateStore" -> "Node.js LightController" : handle_state_change
@enduml
