
@startuml

!include styles.puml

"Any Node.js Component" -> "Node.js State Store": Action Dispatched
"Node.js State Store" -> "Node.js State Store": Action Reduced to State Change
"Node.js State Store" -> "Node.js SCController": State Change Notification
"Node.js SCController" -> "SuperCollider TawController": State Change Notification
"SuperCollider TawController" -> "SuperCollider TawController": Set State
"Any SuperCollider Component" -> "Node.js State Store": Action Dispatched
"Node.js State Store" -> "Node.js State Store": Action Reduced to State Change
"Node.js State Store" -> "Node.js SCController": State Change Notification
"Node.js SCController" -> "SuperCollider TawController": State Change Notification
"SuperCollider TawController" -> "SuperCollider TawController": Set State

@enduml
