@startuml
!include styles.puml
"Node.js StateStore" -> "Node.js StateStore": init => sequencer.transport.beat = 0
"Node.js StateStore" -> "Node.js StateStore": reduce_action => sequencer.transport.beat = 1
"Node.js StateStore" -> "Node.js LightController" : handle_state_change
@enduml
