skinparam backgroundColor transparent
skinparam defaultFontName Monaco
hide circle
skinparam class {
  backgroundColor Azure
  borderColor DarkGrey
  arrowColor Black
  fontColor Black
}
skinparam state {
  backgroundColor Azure
  borderColor DarkGrey
  arrowColor Black
  fontColor Black
}
skinparam sequenceParticipant {
  backgroundColor Azure
  borderColor DarkGrey
}
skinparam sequenceLifeLine {
  borderColor DarkGrey
}
skinparam sequence {
  arrowColor Black
}
skinparam component {
  backgroundColor Azure
  borderColor DarkGrey
}
skinparam interface {
  backgroundColor Azure
  borderColor DarkGrey
}
